# Generated by Django 2.2.3 on 2019-08-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('contact', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
